### PR TITLE
ci: fix vulnerable library versions

### PR DESCRIPTION
**Pull request by mishomihov00**
**Description**:

Changed some library versions, according to the recommendations from Snyk.

**Related issue(s)**:

Related to #1645 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by agadzhalov** [comment]
I am a bit reserved on the upgrading of the `Expo` version overall the CI checks are passing @ivaylonikolov7 had some issues with this and we've postponed it. @mishomihov00 you can follow the discussion in [here](https://github.com/hashgraph/hedera-sdk-js/issues/2361)

**Comment by mishomihov00** [comment]
@agadzhalov I've downgraded the version back to 49.0.16

**Comment by mishomihov00** [comment]
@agadzhalov Can you please take a look at this PR and approve if everything seems ok. Thansk!

**Review by agadzhalov — APPROVED** [review]
LGTM, ty @mishomihov00

**Review by ivaylogarnev-limechain — APPROVED** [review]
LGTM

**Review by ivaylonikolov7 — APPROVED** [review]

**Pull request merged**
